# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'WangYiYun' do
pod 'NodeMobile', :git => 'https://github.com/janeasystems/nodejs-mobile.git'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WangYiYun

  target 'WangYiYunTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
